service: stonks

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  environment:
    RAPIDAPI_HOST: apidojo-yahoo-finance-v1.p.rapidapi.com
    RAPIDAPI_KEY: 8673d8f684msha909b32f0a5d086p14702ejsn01a0c0fcba73

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:DescribeTable
    Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  symbols:
    handler: add-symbols.main
    events:
      - http:
          path: watchlist
          method: post
  watchlist:
    handler: create-watchlist.main
    events:
      - http:
          path: watchlist
          method: post