service: stonks

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  environment:
    RAPIDAPI_HOST: apidojo-yahoo-finance-v1.p.rapidapi.com
    RAPIDAPI_KEY: ${env:RAPIDAPI_KEY}

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:DescribeTable
    Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  add-symbols:
    handler: add-symbols.main
    events:
      - http:
          path: symbols
          method: post
          authorizer: aws_iam
          cors: true
  create-watchlist:
    handler: create-watchlist.main
    events:
      - http:
          path: watchlist
          method: post
          authorizer: aws_iam
          cors: true
  delete-watchlist:
    handler: delete-watchlist.main
    events:
      - http:
          path: watchlist
          method: delete
          authorizer: aws_iam
          cors: true
  get-watchlists:
    handler: get-watchlists.main
    events:
      - http:
          path: watchlist
          method: get
          authorizer: aws_iam
          cors: true